version: 2
updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
    groups:
      dart-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
