name: open_route_service
description: An encapsulation made around openrouteservice APIs, for Dart and Flutter projects, to easily generate Routes and their data. 
version: 1.2.1
repository: https://github.com/dhi13man/open_route_service/
homepage: https://github.com/dhi13man/open_route_service/
issue_tracker: https://github.com/Dhi13man/open_route_service/issues

environment:
  sdk: '>=2.14.1 <3.0.0'

dependencies: 
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
